### ISSUE TITLE
remove expand strip

### ISSUE THREAD

**Issue by TrySound** [jonschlinkert/load-plugins#6]
I think this feature is excessive. Better to use native arrays instead of "some language".

**Comment by jonschlinkert** [comment]
I'm not sure what you mean by this. Are you referring to [the brace expansion feature](https://github.com/jonschlinkert/load-plugins/blob/master/test/test.js#L25-L26)?

**Comment by TrySound** [comment]
@jonschlinkert Yes. But you use it to expand strip opt.

**Comment by jonschlinkert** [comment]
ah, got it. I'm fine with getting rid of that. you're right it's unnecessary.
